-- 코드를 입력하세요
SELECT A.AUTHOR_ID,C.AUTHOR_NAME, A.CATEGORY, SUM(B.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A
LEFT JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR C ON A.AUTHOR_ID = C.AUTHOR_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC