-- 코드를 입력하세요
-- 중성화 o : Neutered, Spayed
-- 중성화 X : Intact

SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A
LEFT OUTER JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (B.SEX_UPON_INTAKE LIKE 'Intact%') AND (A.SEX_UPON_OUTCOME LIKE 'Neutered%' OR A.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY A.ANIMAL_ID;