-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, SUM(PRICE) AS TOTAL
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID AND A.STATUS = 'DONE'
GROUP BY A.WRITER_ID
HAVING TOTAL >= 700000
ORDER BY TOTAL ASC