SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
LEFT JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
LEFT JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1
